# require 'pry'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

install! 'cocoapods',
:generate_multiple_pod_projects => false,
:incremental_installation => false

target 'App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for App
  pod 'OrzOrderFile', :path => '../'
  
end

def custom_target_build_settings(target)
  target.build_configurations.each do |build_configuration|
    # for objective-c
    other_cflags = build_configuration.build_settings['OTHER_CFLAGS']
    build_configuration.build_settings['OTHER_CFLAGS'] = ['$(inherited)',other_cflags, '-fsanitize-coverage=func,trace-pc-guard'].flatten.uniq.compact
    # for swift
    other_swift_flags = build_configuration.build_settings['OTHER_SWIFT_FLAGS']
    if other_swift_flags.is_a?(String)
      other_swift_flags = other_swift_flags.split("\s").uniq
    end
    build_configuration.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)',other_swift_flags, '-sanitize-coverage=func,trace-pc-guard','-sanitize=undefined'].flatten.uniq.compact
  end
end

post_install do |installer|

  # 改变主工程设置
  installer.aggregate_targets.each do |aggregate_target|
    project_path = aggregate_target.user_project.path
    project = Xcodeproj::Project.open(project_path)
    project.targets.each do |target|
      # 只有主工程添加，扩展Target不添加
      unless target.extension_target_type?
        custom_target_build_settings(target)
      end
    end
    project.save
  end
  
  # 改变所有pods的设置
  installer.pods_project.targets.each do |target|
    custom_target_build_settings(target)
  end
  
end
